x-common-environment: &common-environment
    TZ: Asia/Seoul

services:
    nginx:
        environment:
            <<: *common-environment
        image: nginx:alpine
        ports:
            - 80:80 # 호스트 포트(왼쪽)을 컨테이너의 80포트에 매핑
        volumes:
            - ./client/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./client/nginx/common:/etc/nginx/common
            - ./client/dist:/token_meter_dist
        networks:
            - token_meter_network
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '3'

    token_server:
        environment:
            <<: *common-environment
        image: node:20-alpine
        volumes:
            - ./server:/server
            - /server/node_modules
        working_dir: /server
        command: >
            sh -c "
                apk update &&
                apk add --no-cache sqlite sqlite-libs sqlite-dev
                npm install &&
                npm run server
              "
        networks:
            - token_meter_network
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '3'

networks:
    token_meter_network:
        name: token_meter_network
        driver: bridge
