FROM node:20-alpine  

# Step 2: 기본 패키지 업데이트 및 종속성 설치  
RUN apk update && apk add --no-cache \  
    nginx \  
    sqlite \  
    sqlite-libs \  
    sqlite-dev \  
    && rm -rf /var/cache/apk/*

# Step 3: Nginx 설정 파일 설치  
RUN mkdir -p /run/nginx  