x-common-environment: &common-environment
    TZ: Asia/Seoul

services:
    nginx:
        environment:
            <<: *common-environment
        image: nginx:alpine
        ports:
            - ${NGINX_PORT}:80 # 호스트의 포트를 컨테이너의 80 포트에 매핑
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/common:/etc/nginx/common
            - ./client/dist:/token_meter_dist
        networks:
            - token_meter_network
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '3'

    token_server:
        environment:
            <<: *common-environment
        image: node:23.11-bullseye-slim
        volumes:
            - ./server:/server
        working_dir: /server
        command: >
          sh -c "apt update &&
                apt install -y build-essential python3 &&
                npm install &&
                npm run server"
        networks:
            - token_meter_network
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '3'

networks:
    token_meter_network:
        name: token_meter_network
        driver: bridge
