# 1. 기본 노드 이미지를 사용합니다 (바탕으로 사용할 Node 버전을 설정)  
FROM node:20.18.1-alpine3.21 AS build  

WORKDIR /client

COPY ./client ./  
RUN npm install  

RUN npm run build  

WORKDIR /server

COPY ./server ./
RUN npm install

# Step 6: Nginx를 통해 서빙 단계  
# Nginx 및 SQLite 포함된 Base 이미지를 재사용  
FROM token_meter_base

WORKDIR /  

# React 빌드 파일을 Nginx 기본 경로로 복사  
COPY --from=build /client/dist /usr/share/nginx/html  

# Express 서버 관련 파일 복사  
COPY --from=build /server /server  

# Nginx 설정 파일 복사 (React와 API 라우팅 구분 설정을 예로 듦)  
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf  

# 두 개의 프로세스를 실행하기 위한 스크립트 복사 및 실행 권한 부여  
COPY start.sh /start.sh  
RUN chmod +x /start.sh  

# 외부 접근 가능한 포트  NGINX, EXPRESS
EXPOSE 80
EXPOSE 3000

CMD ["/start.sh"]  