x-common-environment: &common-environment
    TZ: Asia/Seoul

services:
    nginx:
        environment:
            <<: *common-environment
        image: cornpip77/token-meter-nginx:latest
        ports:
            - 80:80 # host:container
        networks:
            - token_meter_network
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '3'

    token_server:
        environment:
            <<: *common-environment
        image: cornpip77/token-meter-server:latest
        networks:
            - token_meter_network
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '3'

    # runtime: nvidia option is available in compose version 2 and above.
    token_ai:
        environment:
            <<: *common-environment
        image: cornpip77/token-meter-ai:latest
        runtime: nvidia
        networks:
            - token_meter_network
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '3'
        shm_size: 1g
        
networks:
    token_meter_network:
        name: token_meter_network
        driver: bridge
