x-common-environment: &common-environment
    TZ: Asia/Seoul

services:
    nginx:
        environment:
            <<: *common-environment
        image: cornpip77/token-meter-nginx:latest
        ports:
            - 80:80 # host:container
        networks:
            - token_meter_network
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '3'

    token_server:
        environment:
            <<: *common-environment
        image: cornpip77/token-meter-server:latest
        networks:
            - token_meter_network
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '3'

networks:
    token_meter_network:
        name: token_meter_network
        driver: bridge
