# Base image
FROM huggingface/transformers-pytorch-gpu:latest

# Set working directory
WORKDIR /app

# Install FastAPI and other required packages
RUN pip install --upgrade pip \
    && pip install "fastapi[all]"

# Clone and install sam2
RUN git clone https://github.com/facebookresearch/sam2.git \
    && cd sam2 \
    && pip install -e .

# Expose port (optional, for FastAPI app)
EXPOSE 7775

# Default command
CMD ["/bin/bash"]